environment:
  name: prod
  project: cdf-bootcamp-41-prod
  type: prod
  selected:
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee
variables:
  modules:
    bootcamp:
      CDF_PROJECT: cdf-bootcamp-41-prod # ex. cdf-bootcamp-01-prod
      IDP_CLIENT_ID: ${IDP_CLIENT_ID} # replaced by .env
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET} # replaced by .env
      IDP_TENANT_ID: ${IDP_TENANT_ID} # replaced by .env
      # This is related to the cluster where the CDF project is hosted.
      CDF_URL: https://westeurope-1.cognitedata.com
      IDP_SCOPES: https://westeurope-1.cognitedata.com/.default
      IDP_TOKEN_URL: ${IDP_TOKEN_URL} # replaced by .env
      # Groups
      # OBJECT ID FOR PROD/PROD DATA PIPELINE OEE ENTRA GROUP
      data_developer_source_id: 2793a2f1-cc41-4701-9f58-017bea818637
      data_pipeline_oee_source_id: b8f7c0a2-b46c-4fef-a10c-4de7fad249e7
      # OBJECT ID FOR PROD/PROD ADMIN TK ENTRA GROUP
      readwrite_source_id: 2581db94-1c0b-4f80-be02-c7460d5b3b90
      # OBJECT ID FOR PROD/PROD ADMIN TK ENTRA GROUP
      readonly_source_id: 2581db94-1c0b-4f80-be02-c7460d5b3b90
      # OBJECT ID FOR PROD/PROD ICAPI EXTRACTORS ENTRA GROUP
      icapi_extractors_source_id: 7f35af90-392f-45c4-b5a4-e946071f9618
      # Client Ids
      data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID} # replaced by .env
      data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET} # replaced by .env
      icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID} # replaced by .env
      icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET} # replaced by .env
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi
      use_cases:
        oee:
          uc_oee_ds_external_id: ds_uc_oee